-- =========================================================
-- CARREGAR 140 PERGUNTAS ESTRUTURADAS
-- Execute QUARTO: Carrega todas as perguntas base em português
-- =========================================================

-- 1. INSERIR AS 140 PERGUNTAS ESTRUTURADAS
INSERT INTO public.question_pool (gift, source, pclass, reverse_scored, default_weight, text)
VALUES
('A_PROPHECY','QUALITY','P1',false,1.000,'Quando exponho a Palavra, busco chamar o pecado pelo nome e apontar o caminho da verdade.'),
('A_PROPHECY','QUALITY','P1',false,1.000,'Sinto-me incumbido de proclamar a vontade de Deus ainda que isso me torne impopular.'),
('A_PROPHECY','QUALITY','P1',false,1.000,'Valido minhas convicções pela Escritura antes de exortá‑las aos outros.'),
('A_PROPHECY','QUALITY','P1',false,1.000,'Anseio que pessoas tomem decisões claras diante da verdade apresentada.'),
('A_PROPHECY','QUALITY','P2',false,1.000,'Busco comunicar a mensagem com franqueza e precisão, evitando ambiguidades.'),
('A_PROPHECY','CHARACTERISTIC','P2',false,1.000,'Costumo discernir motivos e padrões por trás de atitudes e escolhas.'),
('A_PROPHECY','CHARACTERISTIC','P2',false,1.000,'Fico entristecido com o pecado do povo e me identifico com sua necessidade de arrependimento.'),
('A_PROPHECY','CHARACTERISTIC','P2',false,1.000,'Vejo assuntos em termos de certo e errado, sem tons de cinza morais.'),
('A_PROPHECY','CHARACTERISTIC','P3',false,1.000,'Procuro evidências externas de convicção interna (frutos de arrependimento).'),
('A_PROPHECY','CHARACTERISTIC','P3',false,1.000,'Busco quebrantamento pessoal antes de conclamar outros ao quebrantamento.'),
('A_PROPHECY','CHARACTERISTIC','P1',false,1.000,'Zelo pela reputação de Deus e pela pureza da Igreja.'),
('A_PROPHECY','DANGER','P1',true,1.000,'Tendo oportunidade de pregar, priorizo parecer brilhante em vez de depender do Espírito.'),
('A_PROPHECY','DANGER','P2',true,1.000,'Confio tanto na minha lógica e retórica que descuido da oração e preparação humilde.'),
('A_PROPHECY','DANGER','P2',true,1.000,'Enxergo pessoas mais como ‘plateia’ do que como indivíduos com necessidades reais.'),
('A_PROPHECY','DANGER','P1',true,1.000,'Busco falar em público para ser reconhecido, não para edificar.'),
('A_PROPHECY','MISUNDERSTANDING','P2',true,1.000,'Costumo impor padrões sem sensibilidade, criando distância nos relacionamentos.'),
('A_PROPHECY','MISUNDERSTANDING','P3',true,1.000,'Ajo de modo tão binário que pareço intolerante a nuances legítimas.'),
('A_PROPHECY','OTHER','P2',false,1.000,'Ao corrigir, procuro unir verdade e amor, evitando ferir desnecessariamente.'),
('A_PROPHECY','OTHER','P3',false,1.000,'Antes de exortar, busco ouvir e compreender o contexto da pessoa.'),
('B_SERVICE','QUALITY','P1',false,1.000,'Percebo necessidades práticas rapidamente e me movo para supri‑las sem ser solicitado.'),
('B_SERVICE','QUALITY','P1',false,1.000,'Sinto alegria genuína em servir nos bastidores para que outros floresçam.'),
('B_SERVICE','QUALITY','P2',false,1.000,'Tenho disposição para trabalhos manuais e tarefas que exigem esforço.'),
('B_SERVICE','QUALITY','P1',false,1.000,'Sou constante e confiável no cumprimento de responsabilidades.'),
('B_SERVICE','QUALITY','P2',false,1.000,'Disponibilizo recursos próprios para evitar atrasos quando há uma necessidade legítima.'),
('B_SERVICE','CHARACTERISTIC','P2',false,1.000,'Gosto de concluir tarefas e me sinto incomodado quando algo fica inacabado.'),
('B_SERVICE','CHARACTERISTIC','P2',false,1.000,'Recordo preferências e detalhes que ajudam a servir melhor as pessoas.'),
('B_SERVICE','CHARACTERISTIC','P3',false,1.000,'Prefiro metas presentes e tangíveis a objetivos excessivamente distantes.'),
('B_SERVICE','CHARACTERISTIC','P2',false,1.000,'Peço instruções claras para executar com excelência.'),
('B_SERVICE','CHARACTERISTIC','P3',false,1.000,'Aprecio colaborar sob liderança, sem necessidade de protagonismo.'),
('B_SERVICE','CHARACTERISTIC','P2',false,1.000,'Organizo ferramentas e materiais para facilitar o serviço contínuo.'),
('B_SERVICE','DANGER','P1',true,1.000,'Assumo mais tarefas do que consigo cumprir, por dificuldade de dizer não.'),
('B_SERVICE','DANGER','P2',true,1.000,'Fico irritado quando meu serviço é atrapalhado por complicações ‘desnecessárias’.'),
('B_SERVICE','DANGER','P2',true,1.000,'Valorizo tanto o fazer que ignoro as pessoas e seus sentimentos.'),
('B_SERVICE','DANGER','P1',true,1.000,'Sirvo esperando reconhecimento e fico magoado quando não recebo agradecimento.'),
('B_SERVICE','MISUNDERSTANDING','P3',true,1.000,'Insisto tanto em ajudar que pareço não aberto a também ser ajudado.'),
('B_SERVICE','MISUNDERSTANDING','P2',true,1.000,'Ao suprir rápido, posso impedir lições que Deus quer ensinar à pessoa.'),
('B_SERVICE','OTHER','P2',false,1.000,'Procuro equilibrar serviço prático com oração e cuidado espiritual.'),
('B_SERVICE','OTHER','P3',false,1.000,'Busco comunicar limites saudáveis para servir com qualidade e constância.'),
('C_TEACHING','QUALITY','P1',false,1.000,'Aproximo‑me do texto bíblico com rigor, buscando o sentido pretendido pelo autor.'),
('C_TEACHING','QUALITY','P1',false,1.000,'Organizo conteúdos de modo sistemático e progressivo.'),
('C_TEACHING','QUALITY','P1',false,1.000,'Valorizo a precisão de termos e contextos nas passagens bíblicas.'),
('C_TEACHING','QUALITY','P2',false,1.000,'Confirmo ideias novas por meio de princípios bíblicos sólidos.'),
('C_TEACHING','QUALITY','P1',false,1.000,'Busco aplicar o ensino à vida, não apenas transmitir informação.'),
('C_TEACHING','CHARACTERISTIC','P2',false,1.000,'Sinto prazer em pesquisar e preparar materiais que beneficiem outros mestres e pregadores.'),
('C_TEACHING','CHARACTERISTIC','P2',false,1.000,'Questiono afirmações sem base e procuro evidências confiáveis.'),
('C_TEACHING','CHARACTERISTIC','P2',false,1.000,'Evito usar textos fora de contexto para ilustrar pontos.'),
('C_TEACHING','CHARACTERISTIC','P3',false,1.000,'Aprofundo‑me mais na pesquisa do que na apresentação em si.'),
('C_TEACHING','CHARACTERISTIC','P2',false,1.000,'Transformo conhecimento em passos práticos para a vida cristã.'),
('C_TEACHING','CHARACTERISTIC','P3',false,1.000,'Antevejo dúvidas dos ouvintes e as abordo no preparo.'),
('C_TEACHING','DANGER','P1',true,1.000,'Sinto-me superior por meu conhecimento e desmereço quem sabe menos.'),
('C_TEACHING','DANGER','P2',true,1.000,'Acumulo informação e adio decisões por esperar ‘ter todos os dados’.'),
('C_TEACHING','DANGER','P2',true,1.000,'Concentro-me tanto em conteúdo que esqueço necessidades dos alunos.'),
('C_TEACHING','DANGER','P3',true,1.000,'Uso detalhes técnicos desnecessários que tornam a aula árida.'),
('C_TEACHING','MISUNDERSTANDING','P2',true,1.000,'Minha busca por precisão parece frieza ou pouca aplicação prática.'),
('C_TEACHING','MISUNDERSTANDING','P3',true,1.000,'Ao provar posições, pareço orgulhoso ou combativo demais.'),
('C_TEACHING','OTHER','P2',false,1.000,'Incluo exemplos e estudos de caso que iluminam o princípio bíblico.'),
('C_TEACHING','OTHER','P3',false,1.000,'Peço feedback dos alunos para ajustar ritmo e clareza.'),
('D_EXHORTATION','QUALITY','P1',false,1.000,'Ajudo pessoas a definirem passos práticos rumo à maturidade espiritual.'),
('D_EXHORTATION','QUALITY','P1',false,1.000,'Vejo na tribulação oportunidades de crescimento e comunico essa esperança.'),
('D_EXHORTATION','QUALITY','P1',false,1.000,'Procuro alinhar conselhos com a Escritura e com a situação real da pessoa.'),
('D_EXHORTATION','QUALITY','P2',false,1.000,'Acompanho quem aconselho e celebro pequenos avanços.'),
('D_EXHORTATION','QUALITY','P2',false,1.000,'Estimulo a fé de pessoas desanimadas com ânimo e realismo.'),
('D_EXHORTATION','CHARACTERISTIC','P2',false,1.000,'Sou acessível e aberto, gerando confiança para conversas profundas.'),
('D_EXHORTATION','CHARACTERISTIC','P2',false,1.000,'Percebo quando alguém está receptivo e disposto a agir.'),
('D_EXHORTATION','CHARACTERISTIC','P3',false,1.000,'Trago à memória princípios úteis a partir de experiências humanas validadas pela Bíblia.'),
('D_EXHORTATION','CHARACTERISTIC','P2',false,1.000,'Faço perguntas que ajudam a pessoa a enxergar possibilidades e próximos passos.'),
('D_EXHORTATION','CHARACTERISTIC','P3',false,1.000,'Procuro equilibrar encorajamento, confronto e intercessão.'),
('D_EXHORTATION','CHARACTERISTIC','P2',false,1.000,'Procuro clareza de metas e prazos para manter o foco do aconselhando.'),
('D_EXHORTATION','DANGER','P2',true,1.000,'Dou tantos conselhos que a pessoa não pensa nem decide por si.'),
('D_EXHORTATION','DANGER','P1',true,1.000,'Fico impaciente quando a pessoa muda devagar ou recai.'),
('D_EXHORTATION','DANGER','P2',true,1.000,'Uso textos fora do contexto apenas para reforçar uma aplicação prática.'),
('D_EXHORTATION','DANGER','P3',true,1.000,'Busco os méritos do progresso do aconselhando para mim.'),
('D_EXHORTATION','MISUNDERSTANDING','P2',true,1.000,'Minha ênfase em ação faz parecer que não aprofundo as raízes do problema.'),
('D_EXHORTATION','MISUNDERSTANDING','P3',true,1.000,'Ao estruturar planos, pareço confiar mais no método que no Espírito.'),
('D_EXHORTATION','OTHER','P2',false,1.000,'Antes de orientar, ouço ativamente a história e as emoções da pessoa.'),
('D_EXHORTATION','OTHER','P3',false,1.000,'Trabalho com ‘responsabilidade mútua’ para que o aconselhando participe das soluções.'),
('E_GIVING','QUALITY','P1',false,1.000,'Administro minhas finanças com propósito para poder contribuir generosamente.'),
('E_GIVING','QUALITY','P1',false,1.000,'Sinto alegria em suprir necessidades sem buscar publicidade.'),
('E_GIVING','QUALITY','P1',false,1.000,'Busco ouvir a direção de Deus antes de uma oferta significativa.'),
('E_GIVING','QUALITY','P2',false,1.000,'Prefiro apoiar obras e projetos com frutos comprovados.'),
('E_GIVING','QUALITY','P2',false,1.000,'Procuro motivar outros à liberalidade por meio do meu exemplo.'),
('E_GIVING','CHARACTERISTIC','P2',false,1.000,'Sou sensível a necessidades discretas que poderiam passar despercebidas.'),
('E_GIVING','CHARACTERISTIC','P3',false,1.000,'Sinto-me participante da obra quando posso contribuir para sua continuidade.'),
('E_GIVING','CHARACTERISTIC','P2',false,1.000,'Tenho uma vida simples para liberar mais recursos ao Reino.'),
('E_GIVING','CHARACTERISTIC','P3',false,1.000,'Peço conselhos sábios para definir valores e destinatários.'),
('E_GIVING','CHARACTERISTIC','P2',false,1.000,'Organizo orçamento e reservas para poder ajudar mesmo em imprevistos.'),
('E_GIVING','CHARACTERISTIC','P2',false,1.000,'Invisto com prudência visando impacto duradouro para a missão.'),
('E_GIVING','DANGER','P1',true,1.000,'Uso a contribuição para controlar decisões de um ministério.'),
('E_GIVING','DANGER','P2',true,1.000,'Revelo valores ofertados para impressionar pessoas.'),
('E_GIVING','DANGER','P2',true,1.000,'Atendo toda solicitação imediata sem avaliar se é o melhor para o outro.'),
('E_GIVING','DANGER','P3',true,1.000,'Sinto-me mártir quando minha generosidade não é reconhecida.'),
('E_GIVING','MISUNDERSTANDING','P3',true,1.000,'Minha frugalidade soa como avareza para familiares e amigos.'),
('E_GIVING','MISUNDERSTANDING','P2',true,1.000,'Ao tentar inspirar outros a dar, pareço exercer pressão indevida.'),
('E_GIVING','OTHER','P2',false,1.000,'Equilibro dar com intercessão, comunhão e serviço prático.'),
('E_GIVING','OTHER','P3',false,1.000,'Avalio periodicamente se meus padrões de consumo honram o chamado à generosidade.'),
('F_LEADERSHIP','QUALITY','P1',false,1.000,'Visualizo o quadro geral e estabeleço alvos alcançáveis para o grupo.'),
('F_LEADERSHIP','QUALITY','P1',false,1.000,'Transformo visão em planos, processos e responsáveis claros.'),
('F_LEADERSHIP','QUALITY','P2',false,1.000,'Considero recursos e limitações antes de decidir.'),
('F_LEADERSHIP','QUALITY','P1',false,1.000,'Encorajo e desenvolvimento pessoas delegando com propósito.'),
('F_LEADERSHIP','QUALITY','P2',false,1.000,'Persevero diante de reações negativas quando o objetivo é correto.'),
('F_LEADERSHIP','CHARACTERISTIC','P2',false,1.000,'Prefiro concluir tarefas rapidamente e iniciar o próximo ciclo.'),
('F_LEADERSHIP','CHARACTERISTIC','P2',false,1.000,'Assumo liderança quando percebo um vácuo organizacional.'),
('F_LEADERSHIP','CHARACTERISTIC','P3',false,1.000,'Faço decisões com confiança após ouvir pessoas-chave.'),
('F_LEADERSHIP','CHARACTERISTIC','P2',false,1.000,'Aprecio grandes responsabilidades e respondo bem à pressão.'),
('F_LEADERSHIP','CHARACTERISTIC','P3',false,1.000,'Comunico prioridades de forma simples e mensurável.'),
('F_LEADERSHIP','CHARACTERISTIC','P2',false,1.000,'Celebro publicamente as vitórias e reconheço os que contribuíram.'),
('F_LEADERSHIP','DANGER','P1',true,1.000,'Centralizo decisões por não confiar suficientemente na equipe.'),
('F_LEADERSHIP','DANGER','P2',true,1.000,'Trato pessoas como ‘recursos’ e não como irmãos com necessidades.'),
('F_LEADERSHIP','DANGER','P2',true,1.000,'Imponho meu jeito em vez de servir e persuadir com humildade.'),
('F_LEADERSHIP','DANGER','P3',true,1.000,'Deixo de valorizar e agradecer colaboradores de forma consistente.'),
('F_LEADERSHIP','MISUNDERSTANDING','P3',true,1.000,'Ao delegar muito, pareço ocioso para quem não vê o trabalho invisível.'),
('F_LEADERSHIP','MISUNDERSTANDING','P2',true,1.000,'Ao insistir no objetivo, pareço insensível ao ritmo e limites das pessoas.'),
('F_LEADERSHIP','OTHER','P2',false,1.000,'Incluo momentos de escuta e cuidado pastoral nas rotinas da equipe.'),
('F_LEADERSHIP','OTHER','P3',false,1.000,'Busco direção de Deus e prestação de contas para manter humildade no exercício da liderança.'),
('G_MERCY','QUALITY','P1',false,1.000,'Percebo com facilidade a dor alheia e me aproximo para consolar.'),
('G_MERCY','QUALITY','P1',false,1.000,'Crio ambientes seguros onde pessoas feridas podem se abrir.'),
('G_MERCY','QUALITY','P2',false,1.000,'Procuro palavras e gestos que não machuquem quem já sofre.'),
('G_MERCY','QUALITY','P1',false,1.000,'Disponibilizo tempo e presença para acompanhar processos delicados.'),
('G_MERCY','QUALITY','P2',false,1.000,'Identifico sinceridade de coração e respondo com compaixão adequada.'),
('G_MERCY','CHARACTERISTIC','P2',false,1.000,'Sou paciente com fraquezas repetidas e comemoro pequenos passos.'),
('G_MERCY','CHARACTERISTIC','P2',false,1.000,'Interesso‑me genuinamente por pessoas esquecidas ou marginalizadas.'),
('G_MERCY','CHARACTERISTIC','P3',false,1.000,'Expresso emoções com liberdade apropriada, gerando empatia.'),
('G_MERCY','CHARACTERISTIC','P3',false,1.000,'Procuro apoio quando meu envolvimento emocional fica intenso.'),
('G_MERCY','CHARACTERISTIC','P2',false,1.000,'Alerto outros para atitudes e palavras que podem ferir terceiros.'),
('G_MERCY','CHARACTERISTIC','P2',false,1.000,'Equilibro presença acolhedora com oração e orientação bíblica.'),
('G_MERCY','DANGER','P1',true,1.000,'Tomo decisões principalmente pelas emoções, ignorando a sabedoria.'),
('G_MERCY','DANGER','P2',true,1.000,'Evito confrontar quando é claramente necessário, com medo de ferir.'),
('G_MERCY','DANGER','P2',true,1.000,'Empatizo com quem não quer mudar e acabo reforçando vitimismo.'),
('G_MERCY','DANGER','P3',true,1.000,'Carrego amarguras antigas e me retraio pela insensibilidade alheia.'),
('G_MERCY','MISUNDERSTANDING','P3',true,1.000,'Minha sensibilidade parece ‘drama’ ou falta de bom senso para alguns.'),
('G_MERCY','MISUNDERSTANDING','P2',true,1.000,'Minha proteção de terceiros é interpretada como intromissão indevida.'),
('G_MERCY','OTHER','P2',false,1.000,'Quando necessário, uno ternura com firmeza amorosa para promover cura real.'),
('G_MERCY','OTHER','P3',false,1.000,'Cuido de meus limites emocionais para continuar servindo com alegria.');

-- 2. INSERIR TRADUÇÕES BASE EM PORTUGUÊS
INSERT INTO public.question_translations (question_id, locale, text)
SELECT id, 'pt', text
FROM public.question_pool;

-- 3. LOG DA OPERAÇÃO
INSERT INTO public.migration_log (step, description, executed_at) 
VALUES ('03_load_questions', 'As 140 perguntas carregadas com traduções PT', NOW());

-- 4. VERIFICAÇÃO
SELECT 
  'Perguntas carregadas' as status,
  COUNT(*) as total_perguntas,
  COUNT(DISTINCT gift) as gifts_distintos,
  COUNT(CASE WHEN reverse_scored THEN 1 END) as perguntas_reversas
FROM public.question_pool;

SELECT 
  'Traduções carregadas' as status,
  locale,
  COUNT(*) as total_traducoes
FROM public.question_translations
GROUP BY locale;

-- 140 perguntas carregadas com traduções em português
