-- =========================================================
-- SISTEMA DE DONS ESPIRITUAIS APRIMORADO - COMPATÍVEL COM SISTEMA EXISTENTE
-- Execute APÓS os scripts 01-06 para adicionar dados ricos multilíngues
-- =========================================================

-- ESTE ARQUIVO ASSUME QUE O SISTEMA BASE JÁ FOI CRIADO PELOS SCRIPTS 01-06
-- Extensões, enums, tabelas básicas já existem - apenas adicionamos dados ricos

-- =========================================================
-- VERIFICAR SE SISTEMA BASE EXISTE
-- =========================================================
do $$
begin
  if not exists (select 1 from information_schema.tables where table_name = 'question_pool') then
    raise exception 'ERRO: Execute primeiro os scripts 01-06 para criar o sistema base';
  end if;
  if not exists (select 1 from information_schema.tables where table_name = 'profiles') then
    raise exception 'ERRO: Execute primeiro os scripts 01-06 para criar o sistema base';
  end if;
end$$;

-- =========================================================
-- NOVAS TABELAS DE DADOS RICOS COM LOCALIZAÇÃO
-- =========================================================
create table if not exists public.categories (
  id int generated by default as identity primary key,
  key varchar(50) not null, -- Chave única para identificação
  locale varchar(10) not null default 'pt',
  name varchar(50) not null,
  greek_term varchar(50),
  description text,
  purpose text,
  unique(key, locale)
);

create table if not exists public.spiritual_gifts (
  id int generated by default as identity primary key,
  gift_key public.gift_key not null, -- Link para o sistema de quiz
  locale varchar(10) not null default 'pt',
  category_key varchar(50) not null, -- Referencia categories.key
  name varchar(100) not null,
  definition text,
  biblical_references varchar(200),
  unique(gift_key, locale)
);

create table if not exists public.qualities (
  id int generated by default as identity primary key,
  gift_key public.gift_key not null, -- Referencia direta ao gift_key
  locale varchar(10) not null default 'pt',
  quality_name varchar(100) not null,
  description text,
  order_sequence int,
  unique(gift_key, locale, order_sequence)
);

create table if not exists public.characteristics (
  id int generated by default as identity primary key,
  gift_key public.gift_key not null, -- Referencia direta ao gift_key
  locale varchar(10) not null default 'pt',
  characteristic text not null,
  order_sequence int,
  unique(gift_key, locale, order_sequence)
);

create table if not exists public.dangers (
  id int generated by default as identity primary key,
  gift_key public.gift_key not null, -- Referencia direta ao gift_key
  locale varchar(10) not null default 'pt',
  danger text not null,
  order_sequence int,
  unique(gift_key, locale, order_sequence)
);

create table if not exists public.misunderstandings (
  id int generated by default as identity primary key,
  gift_key public.gift_key not null, -- Referencia direta ao gift_key
  locale varchar(10) not null default 'pt',
  misunderstanding text not null,
  order_sequence int,
  unique(gift_key, locale, order_sequence)
);

create table if not exists public.ministries (
  id int generated by default as identity primary key,
  key varchar(50) not null, -- Chave única para identificação
  locale varchar(10) not null default 'pt',
  name varchar(100) not null,
  definition text,
  biblical_references varchar(200),
  type text check (type in ('PRIMARY','OTHER')) default 'OTHER',
  unique(key, locale)
);

create table if not exists public.manifestations (
  id int generated by default as identity primary key,
  key varchar(50) not null, -- Chave única para identificação
  locale varchar(10) not null default 'pt',
  name varchar(100) not null,
  definition text,
  classification text check (classification in ('DISCERNIMIENTO','DISCERNIMENTO','PODER','POWER','DECLARACAO','DECLARATION')),
  biblical_references varchar(200),
  unique(key, locale)
);

create table if not exists public.manifestation_principles (
  id int generated by default as identity primary key,
  locale varchar(10) not null default 'pt',
  principle text not null,
  order_sequence int,
  unique(locale, order_sequence)
);

create table if not exists public.biblical_activities (
  id int generated by default as identity primary key,
  key varchar(50) not null, -- Chave única para identificação
  locale varchar(10) not null default 'pt',
  activity_name varchar(100) not null,
  biblical_reference varchar(100),
  biblical_text text,
  unique(key, locale)
);

-- =========================================================
-- COMPLEMENTAR SISTEMA EXISTENTE
-- =========================================================
-- O sistema base já foi criado, apenas complementamos se necessário

-- Log da integração
insert into public.migration_log (step, description, executed_at) 
values ('07_enhanced_data', 'Iniciando integração de dados ricos multilíngues', now())
on conflict (step) do update set 
  executed_at = now(),
  description = excluded.description;

-- =========================================================
-- ADICIONAR FOREIGN KEY CONSTRAINTS
-- =========================================================

-- spiritual_gifts -> categories relationship
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints 
    where constraint_name = 'fk_spiritual_gifts_category'
  ) then
    alter table public.spiritual_gifts 
    add constraint fk_spiritual_gifts_category 
    foreign key (category_key, locale) references public.categories(key, locale);
  end if;
end$$;

-- qualities -> spiritual_gifts relationship  
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints 
    where constraint_name = 'fk_qualities_gift'
  ) then
    alter table public.qualities 
    add constraint fk_qualities_gift 
    foreign key (gift_key, locale) references public.spiritual_gifts(gift_key, locale);
  end if;
end$$;

-- characteristics -> spiritual_gifts relationship
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints 
    where constraint_name = 'fk_characteristics_gift'
  ) then
    alter table public.characteristics 
    add constraint fk_characteristics_gift 
    foreign key (gift_key, locale) references public.spiritual_gifts(gift_key, locale);
  end if;
end$$;

-- dangers -> spiritual_gifts relationship
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints 
    where constraint_name = 'fk_dangers_gift'
  ) then
    alter table public.dangers 
    add constraint fk_dangers_gift 
    foreign key (gift_key, locale) references public.spiritual_gifts(gift_key, locale);
  end if;
end$$;

-- misunderstandings -> spiritual_gifts relationship
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints 
    where constraint_name = 'fk_misunderstandings_gift'
  ) then
    alter table public.misunderstandings 
    add constraint fk_misunderstandings_gift 
    foreign key (gift_key, locale) references public.spiritual_gifts(gift_key, locale);
  end if;
end$$;

-- =========================================================
-- ADICIONAR INDICES PARA PERFORMANCE
-- =========================================================

-- Indices para foreign keys
create index if not exists idx_spiritual_gifts_category_locale on public.spiritual_gifts(category_key, locale);
create index if not exists idx_spiritual_gifts_gift_locale on public.spiritual_gifts(gift_key, locale);
create index if not exists idx_qualities_gift_locale on public.qualities(gift_key, locale);
create index if not exists idx_characteristics_gift_locale on public.characteristics(gift_key, locale);
create index if not exists idx_dangers_gift_locale on public.dangers(gift_key, locale);
create index if not exists idx_misunderstandings_gift_locale on public.misunderstandings(gift_key, locale);
create index if not exists idx_ministries_key_locale on public.ministries(key, locale);
create index if not exists idx_manifestations_key_locale on public.manifestations(key, locale);

-- Indices para queries frequentes
create index if not exists idx_categories_locale on public.categories(locale);
create index if not exists idx_spiritual_gifts_locale on public.spiritual_gifts(locale);
create index if not exists idx_qualities_order on public.qualities(gift_key, locale, order_sequence);
create index if not exists idx_characteristics_order on public.characteristics(gift_key, locale, order_sequence);

-- RLS nas novas tabelas (apenas leitura pública)
alter table public.categories enable row level security;
alter table public.spiritual_gifts enable row level security;
alter table public.qualities enable row level security;
alter table public.characteristics enable row level security;
alter table public.dangers enable row level security;
alter table public.misunderstandings enable row level security;
alter table public.ministries enable row level security;
alter table public.manifestations enable row level security;

-- Políticas de leitura pública
do $$
begin
  -- Categories
  if not exists (select 1 from pg_policies where tablename='categories' and policyname='categories_select_all') then
    create policy categories_select_all on public.categories for select using (true);
  end if;
  
  -- Spiritual Gifts
  if not exists (select 1 from pg_policies where tablename='spiritual_gifts' and policyname='spiritual_gifts_select_all') then
    create policy spiritual_gifts_select_all on public.spiritual_gifts for select using (true);
  end if;
  
  -- Qualities
  if not exists (select 1 from pg_policies where tablename='qualities' and policyname='qualities_select_all') then
    create policy qualities_select_all on public.qualities for select using (true);
  end if;
  
  -- Characteristics
  if not exists (select 1 from pg_policies where tablename='characteristics' and policyname='characteristics_select_all') then
    create policy characteristics_select_all on public.characteristics for select using (true);
  end if;
  
  -- Dangers
  if not exists (select 1 from pg_policies where tablename='dangers' and policyname='dangers_select_all') then
    create policy dangers_select_all on public.dangers for select using (true);
  end if;
  
  -- Misunderstandings
  if not exists (select 1 from pg_policies where tablename='misunderstandings' and policyname='misunderstandings_select_all') then
    create policy misunderstandings_select_all on public.misunderstandings for select using (true);
  end if;
  
  -- Ministries
  if not exists (select 1 from pg_policies where tablename='ministries' and policyname='ministries_select_all') then
    create policy ministries_select_all on public.ministries for select using (true);
  end if;
  
  -- Manifestations
  if not exists (select 1 from pg_policies where tablename='manifestations' and policyname='manifestations_select_all') then
    create policy manifestations_select_all on public.manifestations for select using (true);
  end if;
end$$;

-- =========================================================
-- MANTER FUNÇÕES RPC EXISTENTES (que funcionam)
-- =========================================================
-- get_questions_by_locale() - mantém como está
-- calculate_quiz_result() - mantém como está, mas vamos melhorar

-- =========================================================
-- FUNÇÕES ADICIONAIS (NÃO SOBRESCREVER AS EXISTENTES)
-- =========================================================
-- Mantemos as funções existentes: get_questions_by_locale() e calculate_quiz_result()
-- Apenas adicionamos novas funções para dados ricos

-- Nova função para obter detalhes do dom principal com localização
create or replace function public.get_top_gift_details(p_session_id uuid, p_locale varchar(10) default 'pt')
returns table (
  gift_key public.gift_key,
  gift_name text,
  definition text,
  biblical_references text,
  total_weighted numeric,
  question_count bigint,
  category_name text,
  greek_term text
)
language sql stable as $$
  with top_gift as (
    select gift, total_weighted, question_count
    from public.calculate_quiz_result(p_session_id)
    order by total_weighted desc
    limit 1
  )
  select 
    tg.gift,
    sg.name,
    sg.definition,
    sg.biblical_references,
    tg.total_weighted,
    tg.question_count,
    c.name as category_name,
    c.greek_term
  from top_gift tg
  join public.spiritual_gifts sg on sg.gift_key = tg.gift and sg.locale = p_locale
  left join public.categories c on c.key = sg.category_key and c.locale = p_locale;
$$;

-- Função para obter categorias por locale
create or replace function public.get_categories_by_locale(p_locale varchar(10) default 'pt')
returns table (
  key varchar(50),
  name varchar(50),
  greek_term varchar(50),
  description text,
  purpose text
)
language sql stable as $$
  select key, name, greek_term, description, purpose
  from public.categories
  where locale = p_locale
  order by key;
$$;

-- Função para obter ministérios por locale
create or replace function public.get_ministries_by_locale(p_locale varchar(10) default 'pt')
returns table (
  key varchar(50),
  name varchar(100),
  definition text,
  biblical_references varchar(200),
  type text
)
language sql stable as $$
  select key, name, definition, biblical_references, type
  from public.ministries
  where locale = p_locale
  order by case when type = 'PRIMARY' then 1 else 2 end, name;
$$;

-- Função para obter manifestações por locale
create or replace function public.get_manifestations_by_locale(p_locale varchar(10) default 'pt')
returns table (
  key varchar(50),
  name varchar(100),
  definition text,
  classification text,
  biblical_references varchar(200)
)
language sql stable as $$
  select key, name, definition, classification, biblical_references
  from public.manifestations
  where locale = p_locale
  order by classification, name;
$$;

-- Função para obter dados completos de um dom específico
create or replace function public.get_gift_complete_data(p_gift_key public.gift_key, p_locale varchar(10) default 'pt')
returns json
language sql stable as $$
  select json_build_object(
    'gift', json_build_object(
      'key', sg.gift_key,
      'name', sg.name,
      'definition', sg.definition,
      'biblical_references', sg.biblical_references
    ),
    'category', json_build_object(
      'key', c.key,
      'name', c.name,
      'greek_term', c.greek_term,
      'description', c.description,
      'purpose', c.purpose
    ),
    'qualities', (
      select json_agg(
        json_build_object(
          'id', q.order_sequence,
          'quality_name', q.quality_name,
          'description', q.description
        ) order by q.order_sequence
      )
      from public.qualities q
      where q.gift_key = p_gift_key and q.locale = p_locale
    ),
    'characteristics', (
      select json_agg(q.characteristic order by q.order_sequence)
      from public.characteristics q
      where q.gift_key = p_gift_key and q.locale = p_locale
    ),
    'dangers', (
      select json_agg(q.danger order by q.order_sequence)
      from public.dangers q
      where q.gift_key = p_gift_key and q.locale = p_locale
    ),
    'misunderstandings', (
      select json_agg(q.misunderstanding order by q.order_sequence)
      from public.misunderstandings q
      where q.gift_key = p_gift_key and q.locale = p_locale
    )
  )
  from public.spiritual_gifts sg
  left join public.categories c on c.key = sg.category_key and c.locale = p_locale
  where sg.gift_key = p_gift_key and sg.locale = p_locale;
$$;

-- =========================================================
-- POPULAR DADOS COMPLETOS MULTILÍNGUES
-- =========================================================

-- Categorias em Português
insert into public.categories(key, locale, name, greek_term, description, purpose) values
  ('motivations','pt','MOTIVAÇÕES','Karismation','Impulso básico implantado no interior de cada cristão para que Deus expresse Seu amor','Para cada indivíduo ter e segurar'),
  ('ministries','pt','MINISTÉRIOS','Diakonion','Serviço cristão que Deus determina para cada um, para exercer sua motivação','Para a Igreja'),
  ('manifestations','pt','MANIFESTAÇÕES','Energias planerosis','Manifestações do Espírito para capacitar no ministério','Para indivíduos momentaneamente')
on conflict (key, locale) do update
set name=excluded.name, greek_term=excluded.greek_term, description=excluded.description, purpose=excluded.purpose;

-- Categorias em Inglês
insert into public.categories(key, locale, name, greek_term, description, purpose) values
  ('motivations','en','MOTIVATIONS','Karismation','Basic impulse implanted within each Christian for God to express His love','For each individual to have and hold'),
  ('ministries','en','MINISTRIES','Diakonion','Christian service that God determines for each one, to exercise their motivation','For the Church'),
  ('manifestations','en','MANIFESTATIONS','Energias planerosis','Manifestations of the Spirit to enable ministry','For individuals momentarily')
on conflict (key, locale) do update
set name=excluded.name, greek_term=excluded.greek_term, description=excluded.description, purpose=excluded.purpose;

-- Categorias em Espanhol
insert into public.categories(key, locale, name, greek_term, description, purpose) values
  ('motivations','es','MOTIVACIONES','Karismation','Impulso básico implantado en el interior de cada cristiano para que Dios exprese Su amor','Para cada individuo tener y mantener'),
  ('ministries','es','MINISTERIOS','Diakonion','Servicio cristiano que Dios determina para cada uno, para ejercer su motivación','Para la Iglesia'),
  ('manifestations','es','MANIFESTACIONES','Energias planerosis','Manifestaciones del Espíritu para capacitar en el ministerio','Para individuos momentáneamente')
on conflict (key, locale) do update
set name=excluded.name, greek_term=excluded.greek_term, description=excluded.description, purpose=excluded.purpose;

-- Dons Espirituais em Português
insert into public.spiritual_gifts(gift_key, locale, category_key, name, definition, biblical_references) values
  ('A_PROPHECY','pt','motivations','PROFECIA','A motivação divina a revelar motivos e ações injustas através da apresentação da verdade','Rm 12:3-8; 1Pe 4:10; 1Co 12:4'),
  ('B_SERVICE','pt','motivations','MINISTÉRIO','Demonstrar amor suprindo necessidades práticas','Rm 12:3-8; 1Pe 4:10; 1Co 12:4'),
  ('C_TEACHING','pt','motivations','ENSINO','Pesquisar, esclarecer e preparar material bíblico para outros','Rm 12:3-8; 1Pe 4:10; 1Co 12:4'),
  ('D_EXHORTATION','pt','motivations','EXORTAÇÃO','Estimular a fé e aconselhar rumo à ação espiritual','Rm 12:3-8; 1Pe 4:10; 1Co 12:4'),
  ('E_GIVING','pt','motivations','CONTRIBUIÇÃO','Entregar recursos pessoais para expansão de ministérios','Rm 12:3-8; 1Pe 4:10; 1Co 12:4'),
  ('F_LEADERSHIP','pt','motivations','ADMINISTRAÇÃO','Coordenar atividades rumo a um alvo comum','Rm 12:3-8; 1Pe 4:10; 1Co 12:4'),
  ('G_MERCY','pt','motivations','MISERICÓRDIA','Identificar-se com aflitos para consolá-los','Rm 12:3-8; 1Pe 4:10; 1Co 12:4')
on conflict (gift_key, locale) do update
set category_key=excluded.category_key, name=excluded.name, definition=excluded.definition, biblical_references=excluded.biblical_references;

-- Dons Espirituais em Inglês
insert into public.spiritual_gifts(gift_key, locale, category_key, name, definition, biblical_references) values
  ('A_PROPHECY','en','motivations','PROPHECY','The divine motivation to reveal unjust motives and actions through the presentation of truth','Rom 12:3-8; 1Pet 4:10; 1Cor 12:4'),
  ('B_SERVICE','en','motivations','SERVICE','Demonstrate love by supplying practical needs','Rom 12:3-8; 1Pet 4:10; 1Cor 12:4'),
  ('C_TEACHING','en','motivations','TEACHING','Research, clarify and prepare biblical material for others','Rom 12:3-8; 1Pet 4:10; 1Cor 12:4'),
  ('D_EXHORTATION','en','motivations','EXHORTATION','Stimulate faith and counsel toward spiritual action','Rom 12:3-8; 1Pet 4:10; 1Cor 12:4'),
  ('E_GIVING','en','motivations','GIVING','Deliver personal resources for ministry expansion','Rom 12:3-8; 1Pet 4:10; 1Cor 12:4'),
  ('F_LEADERSHIP','en','motivations','LEADERSHIP','Coordinate activities toward a common goal','Rom 12:3-8; 1Pet 4:10; 1Cor 12:4'),
  ('G_MERCY','en','motivations','MERCY','Identify with the afflicted to console them','Rom 12:3-8; 1Pet 4:10; 1Cor 12:4')
on conflict (gift_key, locale) do update
set category_key=excluded.category_key, name=excluded.name, definition=excluded.definition, biblical_references=excluded.biblical_references;

-- Dons Espirituais em Espanhol
insert into public.spiritual_gifts(gift_key, locale, category_key, name, definition, biblical_references) values
  ('A_PROPHECY','es','motivations','PROFECÍA','La motivación divina para revelar motivos y acciones injustas a través de la presentación de la verdad','Rom 12:3-8; 1Ped 4:10; 1Cor 12:4'),
  ('B_SERVICE','es','motivations','SERVICIO','Demostrar amor supliendo necesidades prácticas','Rom 12:3-8; 1Ped 4:10; 1Cor 12:4'),
  ('C_TEACHING','es','motivations','ENSEÑANZA','Investigar, aclarar y preparar material bíblico para otros','Rom 12:3-8; 1Ped 4:10; 1Cor 12:4'),
  ('D_EXHORTATION','es','motivations','EXHORTACIÓN','Estimular la fe y aconsejar hacia la acción espiritual','Rom 12:3-8; 1Ped 4:10; 1Cor 12:4'),
  ('E_GIVING','es','motivations','CONTRIBUCIÓN','Entregar recursos personales para la expansión de ministerios','Rom 12:3-8; 1Ped 4:10; 1Cor 12:4'),
  ('F_LEADERSHIP','es','motivations','ADMINISTRACIÓN','Coordinar actividades hacia un objetivo común','Rom 12:3-8; 1Ped 4:10; 1Cor 12:4'),
  ('G_MERCY','es','motivations','MISERICORDIA','Identificarse con los afligidos para consolarlos','Rom 12:3-8; 1Ped 4:10; 1Cor 12:4')
on conflict (gift_key, locale) do update
set category_key=excluded.category_key, name=excluded.name, definition=excluded.definition, biblical_references=excluded.biblical_references;

-- QUALIDADES COMPLETAS EM PORTUGUÊS (7 para cada dom)
-- PROFECIA - 7 qualidades
insert into public.qualities(gift_key, locale, quality_name, order_sequence) values
  ('A_PROPHECY','pt','Um relacionamento certo com Deus',1),
  ('A_PROPHECY','pt','Honestidade',2),
  ('A_PROPHECY','pt','Humildade',3),
  ('A_PROPHECY','pt','Entusiasmo pela sua mensagem',4),
  ('A_PROPHECY','pt','Amor pelo auditório',5),
  ('A_PROPHECY','pt','Sensibilidade para com os sentimentos do auditório',6),
  ('A_PROPHECY','pt','Autoconfiança',7)
on conflict (gift_key,locale,order_sequence) do nothing;

-- MINISTÉRIO - 7 qualidades  
insert into public.qualities(gift_key, locale, quality_name, order_sequence) values
  ('B_SERVICE','pt','Um desejo de trabalhar',1),
  ('B_SERVICE','pt','Disposição para aceitar responsabilidades',2),
  ('B_SERVICE','pt','Iniciativa de reconhecer serviços que precisam ser feitos',3),
  ('B_SERVICE','pt','Uma afeição e desejo para servir a outros',4),
  ('B_SERVICE','pt','Resistência',5),
  ('B_SERVICE','pt','Alegria',6),
  ('B_SERVICE','pt','Humildade',7)
on conflict (gift_key,locale,order_sequence) do nothing;

-- ENSINO - 7 qualidades
insert into public.qualities(gift_key, locale, quality_name, order_sequence) values
  ('C_TEACHING','pt','Humildade',1),
  ('C_TEACHING','pt','Sinceridade e honestidade',2),
  ('C_TEACHING','pt','Conscientização e escrupulosidade',3),
  ('C_TEACHING','pt','Organização',4),
  ('C_TEACHING','pt','Otimismo',5),
  ('C_TEACHING','pt','Discernimento',6),
  ('C_TEACHING','pt','Paciência',7)
on conflict (gift_key,locale,order_sequence) do nothing;

-- EXORTAÇÃO - 7 qualidades
insert into public.qualities(gift_key, locale, quality_name, order_sequence) values
  ('D_EXHORTATION','pt','Humildade',1),
  ('D_EXHORTATION','pt','Disponibilidade',2),
  ('D_EXHORTATION','pt','Relação certa com Deus e um andar no Espírito',3),
  ('D_EXHORTATION','pt','Paciência',4),
  ('D_EXHORTATION','pt','Disposição para ouvir',5),
  ('D_EXHORTATION','pt','Otimismo',6),
  ('D_EXHORTATION','pt','Diplomacia',7)
on conflict (gift_key,locale,order_sequence) do nothing;

-- CONTRIBUIÇÃO - 7 qualidades
insert into public.qualities(gift_key, locale, quality_name, order_sequence) values
  ('E_GIVING','pt','Amor verdadeiro pelos outros',1),
  ('E_GIVING','pt','Interesse na obra de Deus',2),
  ('E_GIVING','pt','Discernimento',3),
  ('E_GIVING','pt','Sensibilidade à direção de Deus',4),
  ('E_GIVING','pt','Atitude imaterialista',5),
  ('E_GIVING','pt','Desejo de dar',6),
  ('E_GIVING','pt','Humildade',7)
on conflict (gift_key,locale,order_sequence) do nothing;

-- ADMINISTRAÇÃO - 7 qualidades
insert into public.qualities(gift_key, locale, quality_name, order_sequence) values
  ('F_LEADERSHIP','pt','Sabedoria (compreensão das áreas chaves da vida)',1),
  ('F_LEADERSHIP','pt','Integridade (pureza de coração e honestidade exterior)',2),
  ('F_LEADERSHIP','pt','Humildade (visão exata e correta de si mesmo e de seu ministério)',3),
  ('F_LEADERSHIP','pt','Dedicação (disciplina dirigida de si mesmo em seu ministério)',4),
  ('F_LEADERSHIP','pt','Confiança (saber que pode enfrentar qualquer situação que se apresente, com sucesso)',5),
  ('F_LEADERSHIP','pt','Visão (vendo o quadro todo e planejando criativa e realisticamente para o futuro)',6),
  ('F_LEADERSHIP','pt','Decisão (confiante e organizado em suas decisões)',7)
on conflict (gift_key,locale,order_sequence) do nothing;

-- MISERICÓRDIA - 7 qualidades
insert into public.qualities(gift_key, locale, quality_name, order_sequence) values
  ('G_MERCY','pt','Interesse e aceitação pelos outros',1),
  ('G_MERCY','pt','Humildade',2),
  ('G_MERCY','pt','Sinceridade',3),
  ('G_MERCY','pt','Paciência',4),
  ('G_MERCY','pt','Sensibilidade',5),
  ('G_MERCY','pt','Empatia',6),
  ('G_MERCY','pt','Alegria',7)
on conflict (gift_key,locale,order_sequence) do nothing;

-- Adicionar algumas características principais em português
-- PROFECIA - principais características
insert into public.characteristics(gift_key, locale, characteristic, order_sequence) values
  ('A_PROPHECY','pt','Sente necessidade de expressar sua mensagem, verbalmente',1),
  ('A_PROPHECY','pt','Tem capacidade de discernir os motivos e o caráter dos outros',2),
  ('A_PROPHECY','pt','Tem capacidade de identificar, definir e odiar o mal',3),
  ('A_PROPHECY','pt','Está sempre pronto a experimentar quebrantamento para produzi-lo em outros',4),
  ('A_PROPHECY','pt','Depende das escrituras para validar sua autoridade',5)
on conflict (gift_key,locale,order_sequence) do nothing;

-- MINISTÉRIO - principais características  
insert into public.characteristics(gift_key, locale, characteristic, order_sequence) values
  ('B_SERVICE','pt','Tem capacidade de lembrar do que os outros gostam ou não',1),
  ('B_SERVICE','pt','Está sempre atento às necessidades práticas',2),
  ('B_SERVICE','pt','Impulsionado a suprir as necessidades o mais breve possível',3),
  ('B_SERVICE','pt','É de resistência física suficiente para suprir estas necessidades sem pensar no cansaço',4),
  ('B_SERVICE','pt','Está disposto a usar recursos próprios para evitar demora',5)
on conflict (gift_key,locale,order_sequence) do nothing;

-- Ministérios Primários em Português
insert into public.ministries(key, locale, name, definition, biblical_references, type) values
  ('apostle','pt','APÓSTOLO','Alguém enviado pela igreja para um serviço cristão específico','I Co 12:27-28; Ef 4:11','PRIMARY'),
  ('prophet','pt','PROFETA','Alguém que proclama a mensagem de Deus principalmente aos crentes','I Co 12:27-28; Ef 4:11','PRIMARY'),
  ('evangelist','pt','EVANGELISTA','Alguém que proclama a mensagem de Deus aos inconversos','I Co 12:27-28; Ef 4:11','PRIMARY'),
  ('pastor','pt','PASTOR','Alguém que supervisiona um grupo de crentes e cuida das suas necessidades','I Co 12:27-28; Ef 4:11','PRIMARY'),
  ('teacher','pt','MESTRE','Alguém que esclarece e preserva a Verdade','I Co 12:27-28; Ef 4:11','PRIMARY')
on conflict (key, locale) do update
set name=excluded.name, definition=excluded.definition, biblical_references=excluded.biblical_references, type=excluded.type;

-- Outros Ministérios em Português
insert into public.ministries(key, locale, name, definition, biblical_references, type) values
  ('miracles','pt','OPERADORES DE MILAGRES','Alguém que opera sinais e prodígios','I Co 12:28','OTHER'),
  ('healing','pt','DONS DE CURAR','Alguém que opera curas','I Co 12:28','OTHER'),
  ('helps','pt','SOCORROS','Alguém que assiste a liderança no ministério aos necessitados','I Co 12:28','OTHER'),
  ('governments','pt','GOVERNOS','Alguém que guia e dirige a Igreja Local, ou outra obra','I Co 12:28','OTHER'),
  ('tongues','pt','VARIEDADE DE LÍNGUAS','Alguém que fala várias línguas pelo Espírito (Interpretação implícita)','I Co 12:28','OTHER'),
  ('elder','pt','PRESBÍTERO','Alguém que cuida da parte espiritual da igreja','I Tm; Tt','OTHER'),
  ('deacon','pt','DIÁCONO','Alguém separado para servir','I Tm; Tt','OTHER')
on conflict (key, locale) do update
set name=excluded.name, definition=excluded.definition, biblical_references=excluded.biblical_references, type=excluded.type;

-- Dons de Discernimento (Revelação) em Português
insert into public.manifestations(key, locale, name, definition, classification, biblical_references) values
  ('word-wisdom','pt','PALAVRA DE SABEDORIA','Uma revelação do Espírito mostrando como agir em determinada situação','DISCERNIMENTO','I Co 12:7-11'),
  ('word-knowledge','pt','PALAVRA DE CONHECIMENTO','Uma revelação do Espírito mostrando algo desconhecido','DISCERNIMENTO','I Co 12:7-11'),
  ('discerning-spirits','pt','DISCERNIMENTO DE ESPÍRITOS','Capacidade sobrenatural de discernir as atitudes e manifestações de Deus, do homem ou do diabo','DISCERNIMENTO','I Co 12:7-11')
on conflict (key, locale) do update
set name=excluded.name, definition=excluded.definition, classification=excluded.classification, biblical_references=excluded.biblical_references;

-- Dons de Poder em Português
insert into public.manifestations(key, locale, name, definition, classification, biblical_references) values
  ('faith','pt','FÉ','O poder de visualizar algo que Deus quer operar e crer para que aconteça','PODER','I Co 12:7-11'),
  ('gifts-healing','pt','DONS DE CURAR','O poder do Espírito curando e trazendo saúde pela aplicação da Verdade','PODER','I Co 12:7-11'),
  ('working-miracles','pt','OPERAÇÃO DE MILAGRES','Prodígios e maravilhas operados pelo poder do Espírito','PODER','I Co 12:7-11')
on conflict (key, locale) do update
set name=excluded.name, definition=excluded.definition, classification=excluded.classification, biblical_references=excluded.biblical_references;

-- Dons Declarantes (Expressão) em Português
insert into public.manifestations(key, locale, name, definition, classification, biblical_references) values
  ('prophecy','pt','PROFECIA','O Espírito falando através de alguém para a edificação, exortação e consolação de outros','DECLARACAO','I Co 12:7-11'),
  ('kinds-tongues','pt','VARIEDADE DE LÍNGUAS','Capacidade sobrenatural de adorar a Deus em línguas desconhecidas','DECLARACAO','I Co 12:7-11'),
  ('interpretation-tongues','pt','INTERPRETAÇÃO DE LÍNGUAS','A interpretação de Verdades faladas em línguas desconhecidas','DECLARACAO','I Co 12:7-11')
on conflict (key, locale) do update
set name=excluded.name, definition=excluded.definition, classification=excluded.classification, biblical_references=excluded.biblical_references;

-- PRINCÍPIOS DAS MANIFESTAÇÕES EM PORTUGUÊS
insert into public.manifestation_principles(locale, principle, order_sequence) values
  ('pt','Exercer fé',1),
  ('pt','Aumentar ou ir aumentando à medida do ministério',2),
  ('pt','Falar ao ministério responsável',3),
  ('pt','Sob a autoridade do corpo',4)
on conflict (locale, order_sequence) do update
set principle=excluded.principle;

-- ATIVIDADES BÍBLICAS EM PORTUGUÊS
insert into public.biblical_activities(key, locale, activity_name, biblical_reference, biblical_text) values
  ('truth','pt','Declaração da verdade','I Co 14:1; II Tm 4:2','"Segui o amor, e procurai com zelo os dons espirituais, mas principalmente que profetizeis"'),
  ('service','pt','Serviços','Gl 5:13; Gl 3:23-24','"... sede, antes, servos uns dos outros, pelo amor" - "Tudo quanto fizerdes, fazei-o de todo coração"'),
  ('teaching','pt','Ensino','Gl 3:16','"... instruí-vos e aconselhai-vos mutuamente em toda a sabedoria..."'),
  ('exhortation','pt','Exortação','Hb 3:13','"... exortai-vos mutuamente cada dia..."'),
  ('giving','pt','Contribuição','Mt 10:8; Lc 6:38; Rm 12:13','"... de graça recebeste, de graça daí" - "... daí, e dar-se-vos-a..." - "... Compartilhai as necessidades dos santos..."'),
  ('leadership','pt','Administração','I Tm 3:4; Pv 17:2; 16:32; Ef 6:4','"... e que governe bem a sua própria casa..."'),
  ('mercy','pt','Misericórdia','Lc 10:33-37; Gl 3:12; Gl 6:2','Jesus ilustrou a misericórdia na história do bom samaritano - "Revesti-vos... de afetos da misericórdia..." - "Levai as cargas uns dos outros"')
on conflict (key, locale) do update
set activity_name=excluded.activity_name, biblical_reference=excluded.biblical_reference, biblical_text=excluded.biblical_text;

-- =========================================================
-- FUNÇÕES AUXILIARES PARA FACILITAR INTEGRAÇÃO NO FRONTEND
-- =========================================================

-- Função para obter todos os dons com seus dados completos
create or replace function public.get_all_gifts_with_data(p_locale varchar(10) default 'pt')
returns json
language sql stable as $$
  select json_agg(
    json_build_object(
      'key', sg.gift_key,
      'name', sg.name,
      'definition', sg.definition,
      'biblical_references', sg.biblical_references,
      'category', json_build_object(
        'key', c.key,
        'name', c.name,
        'greek_term', c.greek_term,
        'description', c.description,
        'purpose', c.purpose
      ),
      'characteristics', (
        select json_agg(ch.characteristic order by ch.order_sequence)
        from public.characteristics ch
        where ch.gift_key = sg.gift_key and ch.locale = p_locale
      ),
      'qualities', (
        select json_agg(
          json_build_object(
            'id', q.order_sequence,
            'quality_name', q.quality_name,
            'description', q.description
          ) order by q.order_sequence
        )
        from public.qualities q
        where q.gift_key = sg.gift_key and q.locale = p_locale
      ),
      'dangers', (
        select json_agg(d.danger order by d.order_sequence)
        from public.dangers d
        where d.gift_key = sg.gift_key and d.locale = p_locale
      ),
      'misunderstandings', (
        select json_agg(m.misunderstanding order by m.order_sequence)
        from public.misunderstandings m
        where m.gift_key = sg.gift_key and m.locale = p_locale
      )
    ) order by sg.gift_key
  )
  from public.spiritual_gifts sg
  left join public.categories c on c.key = sg.category_key and c.locale = p_locale
  where sg.locale = p_locale;
$$;

-- =========================================================
-- COMENTÁRIOS FINAIS
-- =========================================================

-- Este schema integra:
-- 1. Sistema de 140 perguntas existente (question_pool, weight_matrix, etc.)
-- 2. Novas tabelas de dados ricos multilíngues
-- 3. Funções RPC aprimoradas com suporte a localização
-- 4. Mantém compatibilidade com get_questions_by_locale() e calculate_quiz_result()
-- 5. Adiciona dados completos do PDF em estrutura normalizada e localizada

-- Para usar no frontend:
-- - get_categories_by_locale('pt') -> categorias
-- - get_ministries_by_locale('pt') -> ministérios  
-- - get_manifestations_by_locale('pt') -> manifestações
-- - get_gift_complete_data('A_PROPHECY', 'pt') -> dados completos de um dom
-- - get_all_gifts_with_data('pt') -> todos os dons com dados completos

-- PRONTO! Schema completo e multilíngue integrado com sistema existente